const homeLinksObjArr = [
  {
    id: "tsqlHub",
    linkName: "tsqlHub",
    imgURL: "/img/homePage/tsql_crop_inv.jpg",
    altImg: "tsql_crop_inv.jpg",
    linkURL: "/pages/pg_T-SQL/tsqlHub",
  },
  {
    id: "mySqlHub",
    linkName: "mySqlHub",
    imgURL: "/img/homePage/mysql_crop_inv.jpg",
    altImg: "mysql_crop_inv.jpg",
    linkURL: "/pages/pg_MySQL/mySqlHub",
  },
  {
    id: "unitTypeIMW",
    linkName: "unitTypeIMW",
    imgURL: "/img/homePage/imw_inv.jpg",
    altImg: "imw_inv.jpg",
    linkURL: "/pages/pg_MySQL/unitTypeIMW",
  },
  {
    id: "itemNamerIMW",
    linkName: "itemNamerIMW",
    imgURL: "/img/homePage/imw_inv.jpg",
    altImg: "imw_inv.jpg",
    linkURL: "/pages/pg_MySQL/itemNamerIMW",
  },
  {
    id: "poItemUpdater",
    linkName: "poItemUpdater",
    imgURL: "/img/homePage/imw_inv.jpg",
    altImg: "imw_inv.jpg",
    linkURL: "/pages/pg_MySQL/poItemUpdater",
  },
  {
    id: "imwClicker",
    linkName: "imwClicker",
    imgURL: "/img/homePage/imw_inv.jpg",
    altImg: "imw_inv.jpg",
    linkURL: "/pages/imwClicker/imwClicker",
  },
  {
    id: "stockFilterUPC",
    linkName: "stockFilterUPC",
    imgURL: "/img/homePage/filter1_inv.jpg",
    altImg: "filter1_inv.jpg",
    linkURL: "/pages/pg_MySQL/stockFilterUPC",
  },
  {
    id: "rbInvUpdater",
    linkName: "rbInvUpdater",
    imgURL: "/img/homePage/filter1_inv.jpg",
    altImg: "filter1_inv.jpg",
    linkURL: "/pages/pg_rbInvUpdater/rbInvUpdater_single_file",
  },
  {
    id: "compareUnequalLists",
    linkName: "compareUnequalLists",
    imgURL: "/img/homePage/lists1_inv.jpg",
    altImg: "lists1_inv.jpg",
    linkURL: "/pages/pg_MySQL/compareUnequalLists",
  },
  {
    id: "minShelfQty",
    linkName: "minShelfQty",
    imgURL: "/img/homePage/shelfItems1_inv.jpg",
    altImg: "shelfItems1_inv.jpg",
    linkURL: "/pages/pg_MySQL/minShelfQty",
  },
  {
    id: "keheUnfiWSdiff",
    linkName: "keheUnfiWSdiff",
    imgURL: "/img/homePage/costComp1_inv.jpg",
    altImg: "costComp1_inv.jpg",
    linkURL: "/pages/pg_MySQL/keheUnfiWSdiff",
  },
  {
    id: "keheSelectWSdiff",
    linkName: "keheSelectWSdiff",
    imgURL: "/img/homePage/costComp1_inv.jpg",
    altImg: "costComp1_inv.jpg",
    linkURL: "/pages/pg_MySQL/keheSelectWSdiff",
  },
  {
    id: "venProfRanking",
    linkName: "venProfRanking",
    imgURL: "/img/homePage/profits1_inv.jpg",
    altImg: "profits1_inv.jpg",
    linkURL: "/pages/pg_venProfRanking/venProfRanking",
  },
  {
    id: "venProf",
    linkName: "venProf",
    imgURL: "/img/homePage/profits1_inv.jpg",
    altImg: "profits1_inv.jpg",
    linkURL: "/pages/pg_MySQL/venProf",
  },
  {
    id: "cstLstDtl",
    linkName: "cstLstDtl",
    imgURL: "/img/homePage/map_pin1_inv.jpg",
    altImg: "map_pin1_inv.jpg",
    linkURL: "/pages/pg_MySQL/cstLstDtl",
  },
];

export default homeLinksObjArr;
