function blank_imw_creator() {
  let imwToPop = {}
  imwToPop['upc'] = ""
  imwToPop['deptID'] = ""
  imwToPop['deptName'] = ""
  imwToPop['rcptAlias'] = ""
  imwToPop['brand'] = ""
  imwToPop['itemName'] = ""
  imwToPop['size'] = ""
  imwToPop['sugstdRtl'] = ""
  imwToPop['lastCost'] = ""
  imwToPop['charm'] = ""
  imwToPop['autoDiscount'] = ""
  imwToPop['idealMarg'] = ""
  imwToPop['wtPrfl'] = ""
  imwToPop['tax1'] = ""
  imwToPop['tax2'] = ""
  imwToPop['tax3'] = ""
  imwToPop['spclTndr1'] = ""
  imwToPop['spclTndr2'] = ""
  imwToPop['posPrmpt'] = ""
  imwToPop['lctn'] = ""
  imwToPop['altID'] = ""
  imwToPop['altRcptAlias'] = ""
  imwToPop['pkgQnt'] = ""
  imwToPop['imwSKU'] = ""
  imwToPop['splrID'] = ""
  imwToPop['unit'] = ""
  imwToPop['numPkgs'] = ""
  imwToPop['pf1'] = ""
  imwToPop['pf2'] = ""
  imwToPop['pf3'] = ""
  imwToPop['pf4'] = ""
  imwToPop['pf5'] = ""
  imwToPop['pf6'] = ""
  imwToPop['pf7'] = ""
  imwToPop['pf8'] = ""
  imwToPop['onhndQnt'] = ""
  imwToPop['rdrPnt'] = ""
  imwToPop['mcl'] = ""
  imwToPop['rdrQnt'] = ""
  imwToPop['memo'] = ""
  imwToPop['flrRsn'] = ""
  imwToPop['dsd'] = ""
  imwToPop['dscMltplr'] = ""
  imwToPop['csPkgMltpl'] = ""
  imwToPop['ovr'] = ""
}


export {
  blank_imw_creator
};